name: Weekly summary

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: "production"
      NEXT_PUBLIC_PG_CONNECTION_STRING: ${{ secrets.NEXT_PUBLIC_PG_CONNECTION_STRING }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ARBITER_TOKEN }} # Use the PAT to checkout

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Run weekly script
        run: bun scripts/weekly.mjs
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}

      - name: Commit and push if it changed
        run: |
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Last update on ${timestamp}" || exit 0
          git push
        env:
          GIT_TOKEN: ${{ secrets.ARBITER_TOKEN }} # Use the PAT to push
